// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/hello.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7116fbf19896b02, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7116fbf19896b02, []int{1}
}

func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// The request message for the streaming RPC.
type StreamRequest struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamRequest) Reset()         { *m = StreamRequest{} }
func (m *StreamRequest) String() string { return proto.CompactTextString(m) }
func (*StreamRequest) ProtoMessage()    {}
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7116fbf19896b02, []int{2}
}

func (m *StreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamRequest.Unmarshal(m, b)
}
func (m *StreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamRequest.Marshal(b, m, deterministic)
}
func (m *StreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamRequest.Merge(m, src)
}
func (m *StreamRequest) XXX_Size() int {
	return xxx_messageInfo_StreamRequest.Size(m)
}
func (m *StreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamRequest proto.InternalMessageInfo

func (m *StreamRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// The response message for the streaming RPC.
type StreamResponse struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamResponse) Reset()         { *m = StreamResponse{} }
func (m *StreamResponse) String() string { return proto.CompactTextString(m) }
func (*StreamResponse) ProtoMessage()    {}
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7116fbf19896b02, []int{3}
}

func (m *StreamResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamResponse.Unmarshal(m, b)
}
func (m *StreamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamResponse.Marshal(b, m, deterministic)
}
func (m *StreamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamResponse.Merge(m, src)
}
func (m *StreamResponse) XXX_Size() int {
	return xxx_messageInfo_StreamResponse.Size(m)
}
func (m *StreamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamResponse proto.InternalMessageInfo

func (m *StreamResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "api.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "api.HelloReply")
	proto.RegisterType((*StreamRequest)(nil), "api.StreamRequest")
	proto.RegisterType((*StreamResponse)(nil), "api.StreamResponse")
}

func init() { proto.RegisterFile("proto/hello.proto", fileDescriptor_f7116fbf19896b02) }

var fileDescriptor_f7116fbf19896b02 = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x4d, 0x4b, 0x03, 0x31,
	0x10, 0x40, 0xbb, 0xf8, 0x51, 0x1d, 0xfc, 0xa0, 0xa3, 0x87, 0xd2, 0x93, 0x04, 0x2c, 0xbd, 0xb8,
	0x29, 0xd5, 0xbb, 0xe0, 0x45, 0x2f, 0x5e, 0xda, 0x9b, 0xb7, 0xb1, 0x0e, 0xbb, 0x0b, 0x49, 0x33,
	0x26, 0xbb, 0xda, 0x15, 0x7f, 0xbc, 0x98, 0x6d, 0xa0, 0x85, 0xde, 0x66, 0x1e, 0x8f, 0xe4, 0x31,
	0x30, 0x10, 0xef, 0x6a, 0xa7, 0x4b, 0x36, 0xc6, 0xe5, 0x71, 0xc6, 0x03, 0x92, 0x4a, 0x29, 0x38,
	0x7b, 0xf9, 0x67, 0x73, 0xfe, 0x6c, 0x38, 0xd4, 0x88, 0x70, 0xb8, 0x22, 0xcb, 0xc3, 0xec, 0x26,
	0x9b, 0x9c, 0xce, 0xe3, 0xac, 0xc6, 0x00, 0x1b, 0x47, 0x4c, 0x8b, 0x43, 0xe8, 0x5b, 0x0e, 0x81,
	0x8a, 0x24, 0xa5, 0x55, 0xdd, 0xc2, 0xf9, 0xa2, 0xf6, 0x4c, 0x36, 0x3d, 0x76, 0x0d, 0x47, 0x5f,
	0x64, 0x9a, 0x24, 0x76, 0x8b, 0x1a, 0xc3, 0x45, 0xd2, 0x82, 0xb8, 0x55, 0xe0, 0xfd, 0xde, 0xec,
	0x17, 0xfa, 0xcf, 0x9e, 0xb9, 0x66, 0x8f, 0x53, 0x38, 0x59, 0x50, 0x1b, 0x23, 0x70, 0x90, 0x93,
	0x54, 0xf9, 0x76, 0xf4, 0xe8, 0x72, 0x1b, 0x89, 0x69, 0x55, 0x0f, 0x1f, 0xd3, 0x27, 0xaf, 0x5d,
	0x5c, 0x40, 0x8c, 0xd2, 0x4e, 0xe0, 0xe8, 0x6a, 0x87, 0x75, 0x35, 0xaa, 0x37, 0xc9, 0xa6, 0xd9,
	0xd3, 0xc3, 0xdb, 0x8c, 0xd7, 0x64, 0xc5, 0x70, 0xbe, 0x74, 0x56, 0x97, 0xeb, 0x9f, 0xd2, 0x35,
	0xa5, 0x2e, 0xdc, 0xdd, 0x06, 0xeb, 0xc2, 0xcb, 0xb2, 0x3b, 0xe8, 0xb7, 0xf3, 0xe6, 0x43, 0x93,
	0x54, 0xef, 0xc7, 0xf1, 0xb4, 0xf7, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xaf, 0xf1, 0x82, 0xf2,
	0x6f, 0x01, 0x00, 0x00,
}
